# Usage:
#   To build the images:  docker compose build
#   To start up a specific service by name:  docker compose up <service_name>
#   To open an interactive shell to a running container:  docker exec -it <container_name> bash

version: "1.0"
services:
  # Base image containing dependencies.
  base:
    image: klab:base
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        ROS_DISTRO: noetic
      target: base
      ssh:
        - default
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    # Needed to display graphical applications
    privileged: True # WARNING Bad!! TEMP (just for spinnaker debugging)
    environment:
      ## Define any environment variables required for your application here.
      # Allows graphical programs in the container.
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
      - NVIDIA_DRIVER_CAPABILITIES=all
    volumes:
      # Allows graphical programs in the container.
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTHORITY:-$HOME/.Xauthority}:/root/.Xauthority
      # Allows devices to be accessed from the container.
      - /dev:/dev

  # Overlay image containing the example source code.
  # TODO (4.8) change the image and target to match your overlay image.
  overlay1:
    extends: base
    # TODO (4.8) line below
    image: klab:overlay-leafblower
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      # TODO (4.8) line below
      target: overlay-leafblower
    group_add:
      # For arduino
      - dialout

  overlay2:
    extends: overlay1
    # TODO (4.8) line below
    image: klab:overlay-camera
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      # TODO (4.8) line below
      target: overlay-camera
    group_add:
      # For spinakker cameras
      - flirimaging

  # Developer container
  dev:
    extends: overlay2
    image: klab:dev
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      target: dev
      args:
        - UID=1001
        - USERNAME=${USERNAME:-devuser}
    volumes:
      # TODO (4.8) Mount the source code
      # TODO can this be replaced with variable?
      - ./packages/apple_harvesting_leafblower:/overlay_ws/src/apple_harvesting_leafblower:rw
      - ./packages/yolo_v8_seg:/overlay_ws/src/yolo_v8_seg:rw
      - ./packages/raft_stereo_wrapper:/overlay_ws/src/raft_stereo_wrapper:rw
      - ./packages/firefly_camera_driver:/overlay_ws/src/firefly_camera_driver:rw
      - ./packages/tracking_pipeline:/overlay_ws/src/tracking_pipeline:rw
      # Mount share folder for data
      - ./share:/overlay_ws/share:rw
      # Mount catkin build artifacts for faster rebuilds
      - ./.cache/noetic/build/:/overlay_ws/build/:rw
      - ./.cache/noetic/devel/:/overlay_ws/devel/:rw
      # Mount git config to allow git to be used from within the container
      - ${HOME}/.gitconfig:/etc/gitconfig:ro
    user: ${USERNAME:-devuser}
    command: sleep infinity

  nvidia-dev:
    extends: dev
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  # TODO Demo example
  run-leafblower:
    extends: overlay1
    command: roslaunch apple_harvesting_leafblower BlowerServer.launch
